#
# (C) Copyright 2014
# Texas Instruments, <www.ti.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifndef CONFIG_SPL_BUILD
ifdef CONFIG_ADV_OTA_SUPPORT
obj-$(CONFIG_BCB_SUPPORT) += command.o bcb.o
endif
endif
obj-y	+= board.o

